In [1]:
 import matplotlib.pyplot as pp

In [2]:
import numpy as np

In [3]:
from skimage.io import imread

In [4]:
from skimage.transform import resize

In [5]:
import os

In [6]:
target=[]
images=[]
flat_data=[]

In [7]:
datadir = '/content/drive/MyDrive/gait/GaitDatasetA-silh'

In [8]:
categories = ['1' ,'1 (2)','1 (3)',]
for category in categories:
  class_num=categories.index(category)
  path=os.path.join(datadir,category)
  for img in os.listdir(path):
    img_array=imread(os.path.join(path,img))
    img_resized=resize(img_array,(150,150,3))
    flat_data.append(img_resized.flatten())
    images.append(img_resized)
    target.append(class_num)

In [9]:
flat_data=np.array(flat_data)

In [10]:
target=np.array(target)

In [11]:
images=np.array(images)

In [12]:
#split data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(flat_data,target,test_size=0.3)

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [14]:
linear = LinearRegression()

In [15]:
print(x_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [16]:
print(y_train)

[1 2 1 ... 2 1 2]


In [17]:
#ols_predict

In [18]:
print(y_test)

[2 1 2 0 2 1 1 2 2 0 0 0 1 2 2 1 0 1 1 1 0 0 2 0 0 2 1 0 1 2 1 1 1 1 1 1 2
 0 2 0 1 2 1 1 1 1 2 0 2 0 0 2 2 0 0 0 0 1 0 0 1 1 0 1 0 1 0 1 1 0 1 0 0 0
 1 1 2 1 0 2 0 2 0 1 2 0 0 2 0 2 2 1 2 2 1 1 1 2 0 0 2 0 1 2 0 0 2 0 2 0 2
 0 2 1 2 2 0 0 1 2 1 2 1 0 0 2 1 0 0 1 0 0 1 0 2 0 1 1 0 1 2 1 2 1 1 0 0 0
 2 1 2 0 2 0 2 2 1 0 0 2 1 2 1 1 2 0 2 2 0 2 1 0 1 1 0 1 1 1 2 0 1 0 2 1 2
 0 2 2 1 0 2 2 0 2 0 1 2 2 1 1 0 0 1 1 1 0 0 0 0 2 1 2 0 0 1 1 0 1 2 0 1 0
 2 2 2 2 2 0 1 1 1 1 1 2 0 2 2 0 2 2 0 0 1 0 1 0 1 1 1 0 0 0 0 0 0 1 0 0 0
 0 1 1 2 0 1 2 0 0 2 1 1 2 2 0 1 2 2 0 0 0 2 0 0 1 1 2 1 1 2 1 2 0 1 1 0 1
 2 0 0 1 0 2 0 1 2 0 0 0 2 1 2 2 0 0 1 1 0 1 2 0 0 0 0 1 0 1 2 2 0 1 0 0 0
 2 1 2 1 2 2 0 2 0 0 1 0 0 0 1 0 1 2 1 1 0 0 1 1 1 1 0 0 1 1 2 2 2 0 2 1 1
 1 2 0 0 0 0 2 2 2 2 1 1 1 2 2 0 0 1 0 1 2 2 1 1 0 0 1 0 1 0 0 2 2 1 1 0 2
 0 2 1 1 2 1 0 2 1 0 2 0 0 2 0 0 0 1 0 1 2 1 0 0 2 2 2 0 0 0 2 0 1 0 1 2 0
 0 1 2 0 0 1 1 1 1 2 1 0 0 0 1 2 2 0 2 0 1 0 2 1 0 1 2 0 2 2 2 1 0 2 1 2 1
 0 0 2 2 2 0 0 2 1 1 0 0 

In [19]:
print(x_test)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [20]:
linear.fit(x_train, y_train)

LinearRegression()

In [21]:
OLS_predict = linear.predict(x_test)

In [22]:
linear.score(x_test,y_test)

0.9269126900560373

In [23]:
#Constructing the confusion matrix for linear regression classifier
#r2_score(OLS_predict, y_test)

In [24]:
#Fitting Logistic Regression to the training set
from sklearn.svm import SVC

In [25]:
svclassifier = SVC(kernel = 'linear')
svclassifier.fit(x_train, y_train)


SVC(kernel='linear')

In [26]:
#Predicting the test set result
y_pred_S = svclassifier.predict(x_test)
y_pred_S
r2_score(y_pred_S, y_test)

0.9887027406444024

In [27]:
#Fitting Decision Tree classifier to the training set

In [28]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier_dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [29]:
#Predicting the test set result
y_pred_dt = svclassifier.predict(x_test)
y_pred_dt

array([2, 1, 2, 0, 2, 1, 1, 2, 2, 0, 0, 0, 1, 2, 2, 1, 0, 1, 1, 1, 0, 0,
       2, 0, 0, 2, 1, 0, 1, 2, 1, 1, 1, 1, 1, 1, 2, 0, 2, 0, 1, 2, 0, 1,
       1, 1, 2, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 2, 1, 0, 2, 0, 2, 0, 1, 2, 0, 0, 2,
       0, 2, 2, 1, 2, 2, 1, 1, 1, 2, 0, 0, 2, 0, 1, 2, 0, 0, 2, 0, 2, 0,
       2, 0, 2, 1, 2, 2, 0, 0, 1, 2, 1, 2, 1, 0, 0, 2, 1, 0, 0, 1, 0, 0,
       1, 0, 2, 0, 1, 1, 0, 1, 2, 1, 2, 1, 1, 0, 0, 0, 2, 1, 2, 0, 2, 0,
       2, 2, 1, 0, 0, 2, 1, 2, 1, 1, 2, 0, 2, 2, 0, 2, 1, 0, 1, 1, 0, 1,
       1, 1, 2, 0, 1, 0, 2, 1, 2, 0, 2, 2, 1, 0, 2, 2, 0, 2, 0, 1, 2, 2,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 2, 1, 2, 0, 0, 1, 1, 0, 1, 2, 0,
       1, 0, 2, 2, 2, 2, 2, 0, 1, 1, 1, 1, 1, 2, 0, 2, 2, 0, 2, 2, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 2, 0,
       1, 2, 0, 0, 2, 1, 1, 2, 2, 0, 1, 2, 2, 0, 0, 0, 2, 0, 0, 1, 1, 2,
       1, 1, 2, 1, 2, 0, 1, 1, 0, 1, 2, 0, 0, 1, 0,

In [30]:
#Creating the Confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_dt)
r2_score(y_pred_dt, y_test)

0.9887027406444024

In [31]:
#Fitting Random Forest classifiers to the training set
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators=200, criterion="entropy")
classifier_rf.fit(x_train, y_train)
y_pred_rf = classifier_rf.predict(x_test)

In [32]:
#Creating the Confusion matrix
from sklearn.metrics import confusion_matrix
cm_rf = confusion_matrix(y_test, y_pred_rf)
r2_score(y_pred_rf, y_test)

0.9822697577169909

In [33]:
from sklearn.linear_model import Lasso
model_lasso = Lasso(alpha= 0.001)
model_lasso.fit(x_train, y_train)

Lasso(alpha=0.001)

In [34]:
pred_lasso = model_lasso.predict(x_test)
print(np.sqrt(mean_squared_error(pred_lasso, y_test)))

0.2484661812219038


In [35]:
r2_score(y_test,pred_lasso)

0.9080769981808597

In [36]:
from sklearn.linear_model import Ridge
model_r = Ridge(alpha = 0.5, normalize = False, tol = 0.01, solver='auto', random_state=42)
model_r.fit(x_train,y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_base.py:148: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2. Please leave the normalize parameter to its default value to silence this warning. The default behavior of this estimator is to not do any normalization. If normalization is needed please use sklearn.preprocessing.StandardScaler instead.
  warnings.warn(


Ridge(alpha=0.5, normalize=False, random_state=42, tol=0.01)

In [37]:
# predicting the y_test
y_pred_r = model_r.predict(x_test)

In [38]:
#finding score for our model
r2_score(y_pred_r, y_test)

0.9280033917301274